//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RsErrores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsErrores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsErrores", typeof(RsErrores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error autenticación.
        /// </summary>
        internal static string lbErrorAutenticacion {
            get {
                return ResourceManager.GetString("lbErrorAutenticacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error guardando en base de datos.
        /// </summary>
        internal static string lbErrorBaseDeDatos {
            get {
                return ResourceManager.GetString("lbErrorBaseDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comunicación.
        /// </summary>
        internal static string lbErrorComunicacion {
            get {
                return ResourceManager.GetString("lbErrorComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, valide, hace falta información o no está en los límites.
        /// </summary>
        internal static string lbFaltaInformacion {
            get {
                return ResourceManager.GetString("lbFaltaInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, Llame al administrador.
        /// </summary>
        internal static string lbLlameAlAdmin {
            get {
                return ResourceManager.GetString("lbLlameAlAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los datos tiene mal formato.
        /// </summary>
        internal static string lbMalFormato {
            get {
                return ResourceManager.GetString("lbMalFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, valide, los datos ingresados.
        /// </summary>
        internal static string lbValideDatos {
            get {
                return ResourceManager.GetString("lbValideDatos", resourceCulture);
            }
        }
    }
}
