//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RsMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lib_lenguajes.RsMenu", typeof(RsMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string lbBorrar {
            get {
                return ResourceManager.GetString("lbBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea borrar la siguiente información?.
        /// </summary>
        internal static string lbBorrarEntidad {
            get {
                return ResourceManager.GetString("lbBorrarEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string lbCancelar {
            get {
                return ResourceManager.GetString("lbCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string lbCerrar {
            get {
                return ResourceManager.GetString("lbCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetallesImagenes.
        /// </summary>
        internal static string lbDetallesImagenes {
            get {
                return ResourceManager.GetString("lbDetallesImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string lbEntrar {
            get {
                return ResourceManager.GetString("lbEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string lbGuardar {
            get {
                return ResourceManager.GetString("lbGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagenes.
        /// </summary>
        internal static string lbImagenes {
            get {
                return ResourceManager.GetString("lbImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        internal static string lbLimpiar {
            get {
                return ResourceManager.GetString("lbLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidades.
        /// </summary>
        internal static string lbLocalidades {
            get {
                return ResourceManager.GetString("lbLocalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizaciones.
        /// </summary>
        internal static string lbLocalizaciones {
            get {
                return ResourceManager.GetString("lbLocalizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string lbMensaje {
            get {
                return ResourceManager.GetString("lbMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string lbModificar {
            get {
                return ResourceManager.GetString("lbModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string lbNuevo {
            get {
                return ResourceManager.GetString("lbNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        internal static string lbPersonas {
            get {
                return ResourceManager.GetString("lbPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrescar.
        /// </summary>
        internal static string lbRefrescar {
            get {
                return ResourceManager.GetString("lbRefrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir.
        /// </summary>
        internal static string lbSeleccionar {
            get {
                return ResourceManager.GetString("lbSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicaciones.
        /// </summary>
        internal static string lbUbicaciones {
            get {
                return ResourceManager.GetString("lbUbicaciones", resourceCulture);
            }
        }
    }
}
